# Generated by Django 4.1.2 on 2022-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sID', models.CharField(max_length=10)),
                ('term', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
