# Generated by Django 4.0 on 2022-10-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
