# Generated by Django 4.0 on 2022-10-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
